---
# Playbook para a criacao da infraestrutura necessaria na AWS
 - hosts: localhost
   connection: local
   roles:
    - { role: keypair, tags: [ 'keypairs', 'infra' ] }
    - { role: vpc, tags: [ 'vpc', 'infra', 'always' ] }
    - { role: app-ec2, tags: [ 'app-ec2', 'infra' ] }
    - { role: lb, tags: [ 'teampass-lb', 'infra' ] }
    - { role: rds, tags: [ 'db-ec2', 'infra' ] }